Algoritmo "Divisiveis por 4"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gustavo Silva Teixeira
// Data atual  : 01/09/2021
Var
cont:inteiro


Inicio
repita
      se cont mod 4 = 0 entao
      escreval (cont)
      fimse
      cont<-cont+1
      ate cont>199
Fimalgoritmo