Algoritmo "Exemplo_Looping2A"
// Disciplina   : [Lógica de Programação e JavaScript]
// Professor   : Jailson
// Descrição   :
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/09/2021
Var
   // Seção de Declarações das variáveis
   x,r,cont: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   cont<-1
   repita
      leia (x)
      r <- x*3
      escreval (r)
      cont<-cont+1
   ate cont>5
Fimalgoritmo