Algoritmo "EXERCICIO43"
// Disciplina   : [Lógica de Programação e JavaScript]
// Professor   : Jailson
// Descrição   : Para A = V, B = V e C = F, qual o resultado da avaliação das seguintes expressões:
// Autor(a)    : Gustavo Silva Teixeira
// Data atual  : 25/08/2021
Var
   // Seção de Declarações das variáveis

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc.



Fimalgoritmo

